Repository Joystream/atlas, pull requests merged in 2021-05, with the labels that each got.

#547 Fix action bar bugs
  src/shared/components/ActionBar/ActionBar.style.ts
  src/shared/components/ActionBar/ActionBarTransaction.style.ts
  src/shared/components/GlobalStyle/GlobalStyle.tsx
  src/views/studio/CreateEditChannelView/CreateEditChannelView.tsx
  src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.style.ts
  src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx
Labels: review-approved

#563 add text ellipsis overflow in topbar
  src/components/Topbar/StudioTopbar/StudioTopbar.style.tsx
  src/components/Topbar/StudioTopbar/StudioTopbar.tsx
Labels: review-approved

#565 Removed PhotoAvailability filters
  src/components/InfiniteGrids/InfiniteChannelGrid.tsx
Labels: review-approved

#576 Limit grid columns to 6
  src/shared/components/Grid/Grid.tsx
Labels: review-approved

#571 sentry console integration
  package.json
  src/index.tsx
  yarn.lock
Labels: review-approved

#580 Fix transaction-illustration
  src/assets/empty-videos-illustration.svg
  src/assets/transaction-illustration.svg
Labels: review-approved

#579 Update member validation
  src/config/regex.ts
  src/utils/formValidationOptions.ts
  src/views/playground/Playgrounds/PlaygroundValidationForm.tsx
  src/views/studio/CreateEditChannelView/CreateEditChannelView.tsx
  src/views/studio/CreateMemberView/CreateMemberView.tsx
  src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx
Labels: review-approved

#570 Channel cover tweaks
  src/shared/components/ChannelCover/ChannelCover.style.ts
  src/views/studio/CreateEditChannelView/CreateEditChannelView.style.tsx
  src/views/studio/CreateEditChannelView/CreateEditChannelView.tsx
Labels: review-approved

#585 Fix video drop animation on firefox
  src/shared/components/FileSelect/FileDrop.style.ts
  src/shared/components/FileSelect/FileSelect.tsx
  src/shared/components/FileStep/FileStep.tsx
  src/shared/components/MultiFileSelect/MultiFileSelect.tsx
Labels: review-approved

#587 Validate image file on upload
  src/shared/components/MultiFileSelect/MultiFileSelect.tsx
  src/utils/image.ts
Labels: review-approved

#546 Notifications
  src/App.tsx
  src/hooks/useConnectionStatus.tsx
  src/hooks/useSnackbar/useSnackbar.tsx
  src/hooks/useUploadsManager/useUploadsManager.tsx
  src/shared/components/Snackbar/Snackbar.style.ts
  src/views/studio/CreateEditChannelView/CreateEditChannelView.tsx
  src/views/studio/EditVideoSheet/EditVideoSheet.tsx
  src/views/studio/MyUploadsView/AssetsGroupUploadBar/AssetsGroupUploadBar.style.tsx
  src/views/studio/MyVideosView/MyVideosView.tsx
  src/views/studio/StudioLayout.tsx
Labels: review-approved

#530 Handle uploads errors
  package.json
  src/components/Sidenav/StudioSidenav/StudioSidenav.tsx
  src/hooks/useSnackbar/useSnackbar.tsx
  src/hooks/useUploadsManager/types.ts
  src/hooks/useUploadsManager/useUploadsManager.tsx
  src/shared/components/Snackbar/Snackbar.stories.tsx
  src/views/playground/PlaygroundLayout.tsx
  src/views/studio/MyUploadsView/AssetLine/AssetLine.tsx
  src/views/studio/MyUploadsView/AssetsGroupUploadBar/AssetsGroupUploadBar.tsx
  src/views/studio/MyUploadsView/AssetsGroupUploadBar/index.ts
  src/views/studio/MyUploadsView/MyUploadsView.tsx
  yarn.lock
Labels: review-approved

#605 add max-height and scroll to base dialog
  src/components/Dialogs/BaseDialog/BaseDialog.style.ts
  src/components/SignInSteps/AccountStep.style.ts
Labels: review-approved

#619 Video sheet properly reacts to window height change
  package.json
  src/views/studio/EditVideoSheet/EditVideoSheet.tsx
  src/views/studio/EditVideoSheet/animations.ts
  yarn.lock
Labels: review-approved

#598 Empty videos tab
  src/assets/empty-uploads-illustration.svg
  src/assets/theater-mask.svg
  src/views/studio/MyUploadsView/EmptyUploadsView.tsx
  src/views/studio/MyVideosView/EmptyVideosView.tsx
  src/views/studio/MyVideosView/MyVideosView.tsx
Labels: review-approved

#618 add throttle to onUploadProgress
  src/hooks/useUploadsManager/useUploadsManager.tsx
Labels: review-approved

#626 Update sign in views to the latest design
  src/assets/coins.svg
  src/assets/signin-illustration.svg
  src/assets/signin-pattern.svg
  src/components/Topbar/StudioTopbar/StudioTopbar.tsx
  src/components/Topbar/TopbarBase.style.tsx
  src/components/Topbar/TopbarBase.tsx
  src/views/studio/CreateMemberView/CreateMemberView.style.ts
  src/views/studio/SignInJoinView/SignInMainView/SignInMainView.style.ts
  src/views/studio/SignInJoinView/SignInMainView/SignInMainView.tsx
  src/views/studio/SignInJoinView/SignInProcessView/SignInProcessView.style.ts
Labels: review-approved

#633 Tabs bar update
  src/views/studio/EditVideoSheet/EditVideoTabsBar/EditVideoTabsBar.style.ts
  src/views/studio/EditVideoSheet/EditVideoTabsBar/EditVideoTabsBar.tsx
Labels: review-approved

#637 add padding to uploads view, general responsive tweaks
  src/components/Topbar/StudioTopbar/StudioTopbar.style.tsx
  src/components/Topbar/StudioTopbar/StudioTopbar.tsx
  src/views/studio/CreateEditChannelView/CreateEditChannelView.style.tsx
  src/views/studio/MyUploadsView/MyUploadsView.style.tsx
  src/views/studio/MyUploadsView/MyUploadsView.tsx
Labels: review-approved

#621 Fix issue with updating video without thumbnail
  src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx
Labels: review-waiting-for-response

#639 Reset the file select step component on tab change
  src/shared/components/MultiFileSelect/MultiFileSelect.tsx
Labels: review-approved

#630 Fix MyVideos filters
  src/api/client/cache.ts
  src/utils/cachingAssets.ts
  src/views/studio/MyVideosView/MyVideosView.tsx
Labels: review-waiting-for-changes

#638 Handle asset liaison being not active
  src/api/hooks/workers.ts
  src/components/ChannelLink/ChannelLink.tsx
  src/components/ChannelPreview.tsx
  src/components/CoverVideo/CoverVideo.tsx
  src/components/Topbar/StudioTopbar/StudioTopbar.tsx
  src/components/VideoPreview.tsx
  src/hooks/index.ts
  src/hooks/useAsset.tsx
  src/hooks/useEditVideoSheet.tsx
  src/utils/asset.ts
  src/views/playground/Playgrounds/UploadFiles.tsx
  src/views/studio/CreateEditChannelView/CreateEditChannelView.tsx
  src/views/studio/EditVideoSheet/EditVideoSheet.tsx
  src/views/studio/MyUploadsView/AssetLine/AssetLine.tsx
  src/views/viewer/ChannelView/ChannelView.tsx
  src/views/viewer/SearchOverlayView/RecentSearches/previews/RecentChannelPreview.tsx
  src/views/viewer/SearchOverlayView/RecentSearches/previews/RecentVideoPreview.tsx
  src/views/viewer/VideoView/VideoView.tsx
Labels: review-approved

#631 Select video on pullup/edit
  src/views/studio/MyVideosView/MyVideosView.tsx
Labels: review-waiting-for-changes

#652 Fix useAsset hook
  src/hooks/useAsset.tsx
Labels: review-approved

#666 Replace transaction illustration
  src/assets/transaction-illustration.svg
Labels: review-approved

#661 Fix margin/padding issues with EditVideoForm
  src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.style.ts
Labels: review-approved

#668 fix followed channels placement
  src/components/Sidenav/SidenavBase.style.ts
  src/components/Sidenav/SidenavBase.tsx
  src/components/Sidenav/ViewerSidenav/FollowedChannels.style.ts
  src/components/Sidenav/ViewerSidenav/FollowedChannels.tsx
Labels: review-approved

#670 various tweaks
  src/MainLayout.tsx
  src/api/client/cache.ts
  src/components/SignInSteps/ExtensionStep.tsx
  src/components/SignInSteps/SignInStepsStepper.tsx
  src/components/VideoGallery.tsx
  src/views/studio/CreateEditChannelView/CreateEditChannelView.tsx
Labels: review-waiting-for-changes
