Repository Joystream/atlas, pull requests merged in 2021-06, with the labels that each got.

#724 update My uploads header casing
  src/views/studio/MyUploadsView/MyUploadsView.tsx
Labels: review-approved

#748 reset file drop error when it's resolved
  src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx
Labels: review-approved

#754 Add open in tab option in publisher video context menu
  .gitignore
  src/components/VideoPreview.tsx
  src/shared/components/VideoPreviewBase/VideoPreviewBase.tsx
Labels: review-waiting-for-changes

#752 Filter pending videos search
  src/api/queries/__generated__/baseTypes.generated.ts
  src/api/queries/__generated__/search.generated.tsx
  src/api/queries/search.graphql
  src/api/schemas/extendedQueryNode.graphql
  src/views/viewer/SearchOverlayView/SearchResults/SearchResults.tsx
Labels: review-waiting-for-changes

#753 Scrollbar styles
  src/shared/components/GlobalStyle/GlobalStyle.tsx
Labels: review-approved

#787 Don't require attribution for license
  src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx
Labels: review-approved

#773 Check if browser is outdated
  src/App.tsx
  src/MainLayout.tsx
  src/utils/broswer.ts
  src/views/playground/PlaygroundLayout.tsx
  src/views/studio/StudioLayout.tsx
Labels: review-waiting-for-changes

#817 Filter watched video from more videos
  src/components/InfiniteGrids/InfiniteVideoGrid.tsx
  src/views/viewer/VideoView/VideoView.tsx
Labels: status:approved

#813 Storing player volume
  src/hooks/usePersonalData/localStorageClient/localStorageClient.tsx
  src/hooks/usePersonalData/localStorageClient/types.ts
  src/hooks/usePersonalData/usePersonalData.tsx
  src/shared/components/VideoPlayer/VideoPlayer.tsx
Labels: status:approved

#819 Fix video playing when typing on the searh bar
  src/views/viewer/VideoView/VideoView.tsx
Labels: status:needs response

#768 AssetImage component
  src/components/ChannelLink/ChannelLink.tsx
  src/components/ChannelPreview.tsx
  src/components/CoverVideo/CoverVideo.tsx
  src/components/Dialogs/ImageCropDialog/ImageCropDialog.stories.tsx
  src/components/Topbar/StudioTopbar/StudioTopbar.tsx
  src/components/VideoPreview.tsx
  src/hooks/useAsset.tsx
  src/hooks/useAsset/constants.ts
  src/hooks/useAsset/index.ts
  src/hooks/useAsset/useAsset.tsx
  src/hooks/useEditVideoSheet.tsx
  src/shared/components/Avatar/Avatar.stories.tsx
  src/shared/components/Avatar/Avatar.tsx
  src/shared/components/ChannelAvatar/ChannelAvatar.tsx
  src/shared/components/ChannelCover/ChannelCover.stories.tsx
  src/shared/components/ChannelCover/ChannelCover.style.ts
  src/shared/components/ChannelCover/ChannelCover.tsx
  src/shared/components/ChannelPreviewBase/ChannelPreview.stories.tsx
  src/shared/components/ChannelPreviewBase/ChannelPreviewBase.tsx
  src/shared/components/Tooltip/Tooltip.stories.tsx
  src/shared/components/VideoPreviewBase/VideoPreviewBase.tsx
  src/views/studio/CreateEditChannelView/CreateEditChannelView.tsx
  src/views/studio/CreateMemberView/CreateMemberView.tsx
  src/views/studio/SignInView/SignInView.tsx
  src/views/viewer/ChannelView/ChannelView.tsx
  src/views/viewer/SearchOverlayView/RecentSearches/previews/RecentChannelPreview.tsx
  src/views/viewer/SearchOverlayView/RecentSearches/previews/RecentVideoPreview.tsx
  src/views/viewer/VideoView/VideoView.tsx
Labels: status:approved

#849 refactor transaction manager
  src/hooks/useDeleteVideo.tsx
  src/joystream-lib/types.ts
  src/providers/transactionManager.tsx
  src/providers/transactionManager/index.ts
  src/providers/transactionManager/store.ts
  src/providers/transactionManager/transactionManager.tsx
  src/providers/transactionManager/useTransaction.ts
  src/store/index.ts
  src/views/studio/CreateEditChannelView/CreateEditChannelView.tsx
  src/views/studio/EditVideoSheet/EditVideoSheet.tsx
  src/views/studio/StudioLayout.tsx
Labels: status:approved

#919 Small Logger improvement
  src/utils/logger.ts
Labels: status:approved

#915 Remove default draft title
  src/providers/editVideoSheet/hooks.tsx
  src/shared/components/VideoPreviewBase/VideoPreviewBase.tsx
Labels: status:approved

#917 Open studio/viewer in new tab
  src/MainLayout.tsx
  src/components/Sidenav/StudioSidenav/StudioSidenav.tsx
  src/components/Sidenav/ViewerSidenav/ViewerSidenav.tsx
  src/components/VideoPreview.tsx
  src/utils/browser.ts
  src/views/studio/StudioLayout.tsx
Labels: status:approved

#880 add export/import of localStorage
  src/config/envs.ts
  src/views/admin/AdminView.tsx
Labels: status:approved

#844 personalData store
  src/components/InterruptedVideosGallery.tsx
  src/components/Sidenav/ViewerSidenav/FollowedChannels.tsx
  src/components/Sidenav/ViewerSidenav/ViewerSidenav.tsx
  src/providers/personalData/index.ts
  src/providers/personalData/localStorageClient/index.ts
  src/providers/personalData/localStorageClient/localStorageClient.tsx
  src/providers/personalData/localStorageClient/types.ts
  src/providers/personalData/personalData.tsx
  src/providers/personalData/store.tsx
  src/providers/personalData/types.ts
  src/shared/components/DismissibleMessage/DismissibleMessage.stories.tsx
  src/shared/components/DismissibleMessage/DismissibleMessage.tsx
  src/shared/components/VideoPlayer/VideoPlayer.tsx
  src/store/index.ts
  src/views/studio/StudioLayout.tsx
  src/views/viewer/ChannelView/ChannelView.tsx
  src/views/viewer/HomeView.tsx
  src/views/viewer/SearchOverlayView/RecentSearches/RecentSearches.tsx
  src/views/viewer/SearchOverlayView/SearchResults/SearchResults.tsx
  src/views/viewer/VideoView/VideoView.tsx
  src/views/viewer/ViewerLayout.tsx
Labels: status:approved

#916 Use global store for connection status
  src/App.tsx
  src/components/NoConnectionIndicator/NoConnectionIndicator.stories.tsx
  src/providers/connectionStatus.tsx
  src/providers/joystream/provider.tsx
  src/providers/transactionManager/useTransaction.ts
  src/views/playground/PlaygroundLayout.tsx
  src/views/playground/Playgrounds/PlaygroundConnectionState.tsx
  src/views/studio/CreateEditChannelView/CreateEditChannelView.tsx
  src/views/studio/CreateMemberView/CreateMemberView.tsx
  src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx
  src/views/studio/SignInView/SignInView.tsx
  src/views/studio/StudioLayout.tsx
Labels: status:needs changes
