Repository Joystream/atlas, pull requests merged in 2021-09, with the labels that each got.

#1314 Center dialogs vertically
  src/components/Dialogs/BaseDialog/BaseDialog.style.ts
Labels: status:needs response

#1308 Fix disappearing tab when exiting the channel
  src/views/viewer/ChannelView/ChannelView.tsx
Labels: status:approved

#1310 Update secondary icon buttons opacity
  src/shared/components/ButtonBase/ButtonBase.style.ts
Labels: status:approved

#1318 Add ability to click on cover photo while it's loading
  src/shared/components/VideoTileBase/VideoTileBase.styles.tsx
  src/shared/components/VideoTileBase/VideoTileBase.tsx
Labels: status:approved

#1321 Refactor channel follow/unfollow logic
  src/components/ChannelCard.tsx
  src/components/ChannelWithVideos/ChannelWithVideos.tsx
  src/components/Topbar/StudioTopbar/StudioTopbar.tsx
  src/hooks/useHandleFollowChannel.tsx
  src/views/viewer/ChannelView/ChannelView.style.tsx
  src/views/viewer/ChannelView/ChannelView.tsx
Labels: status:approved

#1338 replace AdminView with AdminOverlay
  .env
  src/MainLayout.tsx
  src/components/AdminOverlay/AdminOverlay.style.ts
  src/components/AdminOverlay/AdminOverlay.tsx
  src/components/AdminOverlay/index.ts
  src/components/VideoHero/VideoHeroData.ts
  src/config/availableNodes.ts
  src/config/envs.ts
  src/config/routes.ts
  src/main.tsx
  src/providers/environment/store.ts
  src/providers/joystream/provider.tsx
  src/providers/user/store.ts
  src/shared/components/FormField/FormField.style.ts
  src/shared/components/FormField/FormField.tsx
  src/shared/components/Tabs/Tabs.tsx
  src/views/admin/AdminView.tsx
  src/views/admin/index.ts
Labels: status:approved

#1337 Fix issue with showing big play button when video is not ready to play
  src/shared/components/VideoPlayer/VideoPlayer.style.tsx
  src/shared/components/VideoPlayer/VideoPlayer.tsx
  src/views/viewer/VideoView/VideoView.tsx
Labels: status:needs changes

#1341 Fix issue with not displaying ActionBar primary button
  src/shared/components/ActionBar/ActionBar.tsx
Labels: status:approved

#1343 Refactor `uploadsManager` store
  src/hooks/useDeleteVideo.tsx
  src/providers/uploadsManager/store.ts
  src/providers/uploadsManager/uploadsManager.tsx
  src/providers/uploadsManager/useStartFileUpload.tsx
Labels: status:approved

#1392 Show input helper dynamically
  src/components/AdminOverlay/AdminOverlay.tsx
  src/components/InfiniteGrids/InfiniteChannelWithVideosGrid.tsx
  src/shared/components/FormField/FormField.style.ts
  src/shared/components/HelperText/HelperText.tsx
  src/shared/components/InputBase/InputBase.styles.ts
  src/shared/components/InputBase/InputBase.tsx
  src/views/studio/MyVideosView/MyVideosView.tsx
  src/views/viewer/ChannelView/ChannelView.tsx
Labels: status:approved

#1400 Fix datepicker validation
  src/shared/components/Datepicker/Datepicker.tsx
Labels: status:approved

#1396 Remove size variant in TitleArea
  package.json
  src/shared/components/TitleArea/TitleArea.style.tsx
  src/shared/components/TitleArea/TitleArea.tsx
  src/views/studio/CreateEditChannelView/CreateEditChannelView.tsx
  src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx
  yarn.lock
Labels: status:approved

#1394 Fix not clickable video tile labels
  src/shared/components/VideoTileBase/VideoTileBase.tsx
Labels: status:approved

#1399 Show skeleton for video when assets are loading
  src/shared/components/VideoPlayer/VideoPlayer.tsx
  src/views/viewer/VideoView/VideoView.tsx
Labels: status:approved

#1412 Fix scrollbar behind action bar
  src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.style.ts
  src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx
Labels: status:approved
