Repository Joystream/atlas, pull requests merged in 2021-07, with the labels that each got.

#997 Add popular page
  src/components/Sidenav/ViewerSidenav/ViewerSidenav.tsx
  src/config/routes.ts
  src/views/viewer/PopularView/PopularView.tsx
  src/views/viewer/PopularView/index.ts
  src/views/viewer/ViewerLayout.tsx
  src/views/viewer/index.ts
Labels: status:approved

#989 Remove continue watching section from home page (#958)
  src/components/InterruptedVideosGallery.tsx
  src/components/index.ts
  src/views/viewer/HomeView.tsx
Labels: status:approved

#1018 Add Official Joystream updates section to home page
  .env
  src/components/OfficialJoystreamUpdate.tsx
  src/components/VideoGallery.tsx
  src/components/index.ts
  src/shared/components/Carousel/Carousel.style.ts
  src/shared/components/Gallery/Gallery.style.ts
  src/shared/components/Gallery/Gallery.tsx
  src/views/viewer/HomeView.tsx
Labels: status:needs rebase

#1020 Shortcuts fix
  src/shared/components/VideoPlayer/ControlsIndicator.tsx
  src/shared/components/VideoPlayer/VideoPlayer.tsx
  src/shared/components/VideoPlayer/utils.ts
  src/shared/components/VideoPlayer/videoJsPlayer.ts
  src/views/viewer/VideoView/VideoView.tsx
Labels: status:approved

#1031 Search channel view
  src/api/hooks/channel.ts
  src/api/queries/__generated__/search.generated.tsx
  src/api/queries/search.graphql
  src/components/ChannelPreview.tsx
  src/shared/components/Tabs/Tabs.tsx
  src/shared/components/TextField/TextField.tsx
  src/shared/icons/GlyphSearch.tsx
  src/shared/icons/index.tsx
  src/shared/icons/svgs/glyph-search.svg
  src/views/viewer/ChannelView/ChannelView.style.tsx
  src/views/viewer/ChannelView/ChannelView.tsx
  src/views/viewer/SearchOverlayView/SearchResults/SearchResults.tsx
Labels: status:needs response

#1057 Popular videos query
  src/api/client/cache.ts
  src/api/hooks/channel.ts
  src/api/hooks/video.ts
  src/api/queries/__generated__/baseTypes.generated.ts
  src/api/queries/__generated__/channels.generated.tsx
  src/api/queries/__generated__/videos.generated.tsx
  src/api/queries/channels.graphql
  src/api/queries/videos.graphql
  src/api/schemas/orion.graphql
  src/components/InfiniteGrids/InfiniteVideoGrid.tsx
  src/views/viewer/HomeView.tsx
Labels: status:approved
