Repository Joystream/atlas, pull requests merged in 2021-03, with the labels that each got.

#350 Radio button
  src/shared/components/RadioButton/RadioButton.stories.tsx
  src/shared/components/RadioButton/RadioButton.style.ts
  src/shared/components/RadioButton/RadioButton.tsx
  src/views/Playgrounds/PlaygroundValidationForm.tsx
Labels: review-approved

#361 fix: video is not clickable after introducing "add publisher mode to VideoPreview"
  src/shared/components/VideoPreviewBase/VideoPreviewBase.tsx
Labels: review-approved

#375 Checkout component
  src/shared/components/Checkout/Checkout.stories.tsx
  src/shared/components/Checkout/Checkout.styles.tsx
  src/shared/components/Checkout/Checkout.tsx
  src/shared/components/Checkout/index.tsx
Labels: review-waiting-for-changes

#360 My videos view
  src/api/client/cache.ts
  src/api/hooks/channel.ts
  src/api/hooks/video.ts
  src/api/queries/__generated__/baseTypes.generated.ts
  src/api/queries/__generated__/categories.generated.tsx
  src/api/queries/__generated__/channels.generated.tsx
  src/api/queries/__generated__/videos.generated.tsx
  src/api/queries/channels.graphql
  src/api/queries/videos.graphql
  src/api/schemas/extendedQueryNode.graphql
  src/assets/empty-videos-illustration.svg
  src/assets/well-blue.svg
  src/components/StudioContainer.tsx
  src/components/VideoPreview.tsx
  src/components/index.ts
  src/config/misc.ts
  src/config/routes.ts
  src/hooks/useDrafts/useDrafts.tsx
  src/hooks/useDrafts/utils.ts
  src/mocking/data/mockVideos.ts
  src/mocking/handlers.ts
  src/shared/components/Icon/Icon.tsx
  src/shared/components/Pagination/Pagination.tsx
  src/shared/components/Tooltip/Tooltip.style.ts
  src/shared/components/VideoPreviewBase/PullUp.tsx
  src/shared/components/VideoPreviewBase/VideoPreview.stories.tsx
  src/shared/components/VideoPreviewBase/VideoPreviewBase.styles.tsx
  src/shared/components/VideoPreviewBase/VideoPreviewBase.tsx
  src/shared/components/index.ts
  src/shared/icons/bring-up.svg
  src/shared/icons/index.ts
  src/shared/theme/transitions.ts
  src/utils/broswer.ts
  src/views/consumer/SearchOverlayView/RecentSearches/RecentSearches.tsx
  src/views/index.ts
  src/views/playground/Playgrounds/PlaygroundDrafts.tsx
  src/views/studio/MyVideosView/EmptyVideosView.tsx
  src/views/studio/MyVideosView/MyVideos.styles.ts
  src/views/studio/MyVideosView/MyVideosView.tsx
  src/views/studio/MyVideosView/index.ts
  src/views/studio/StudioRouter.tsx
  src/views/studio/StudioView.tsx
  src/views/studio/index.ts
Labels: review-blocked

#404 make routes absolute
  src/MainLayout.tsx
  src/components/ChannelLink/ChannelLink.tsx
  src/components/ChannelPreview.tsx
  src/components/CoverVideo/CoverVideo.tsx
  src/components/Sidenav/Sidenav.tsx
  src/components/Topbar/StudioTopbar/StudioTopbar.tsx
  src/components/Topbar/ViewerTopbar/ViewerTopbar.tsx
  src/components/VideoPreview.tsx
  src/config/routes.ts
  src/views/studio/StudioLayout.tsx
  src/views/viewer/SearchOverlayView/RecentSearches/previews/RecentChannelPreview.tsx
  src/views/viewer/SearchOverlayView/RecentSearches/previews/RecentVideoPreview.tsx
  src/views/viewer/ViewerLayout.tsx
Labels: review-approved

#384 Signin view
  src/assets/account-creation.png
  src/assets/tile-example.png
  src/assets/video-example.png
  src/components/Dialogs/BaseDialog/BaseDialog.style.ts
  src/components/Dialogs/index.ts
  src/components/StudioContainer.tsx
  src/components/Topbar/StudioTopbar/StudioTopbar.tsx
  src/config/routes.ts
  src/hooks/index.ts
  src/hooks/useActiveUser/useActiveUser.tsx
  src/hooks/useCheckBrowser.tsx
  src/shared/components/Button/Button.style.ts
  src/shared/components/Button/Button.tsx
  src/shared/components/MultiFileSelect/index.ts
  src/shared/components/Spinner/Spinner.stories.tsx
  src/shared/components/Spinner/Spinner.style.ts
  src/shared/components/Spinner/Spinner.tsx
  src/shared/components/Spinner/index.ts
  src/shared/components/index.ts
  src/shared/icons/arrow-down.svg
  src/shared/icons/chrome.svg
  src/shared/icons/firefox.svg
  src/shared/icons/index.ts
  src/shared/icons/profile.svg
  src/utils/formValidationOptions.ts
  src/views/LayoutWithRouting.tsx
  src/views/studio/CreateMemberView/CreateMemberView.style.ts
  src/views/studio/CreateMemberView/CreateMemberView.tsx
  src/views/studio/CreateMemberView/index.ts
  src/views/studio/SelectMembershipView/SelectMembershipView.style.ts
  src/views/studio/SelectMembershipView/SelectMembershipView.tsx
  src/views/studio/SelectMembershipView/Steps/AccountStep.style.ts
  src/views/studio/SelectMembershipView/Steps/AccountStep.tsx
  src/views/studio/SelectMembershipView/Steps/ExtensionStep.style.ts
  src/views/studio/SelectMembershipView/Steps/ExtensionStep.tsx
  src/views/studio/SelectMembershipView/Steps/Steps.style.ts
  src/views/studio/SelectMembershipView/Steps/TermsStep.style.ts
  src/views/studio/SelectMembershipView/Steps/TermsStep.tsx
  src/views/studio/SelectMembershipView/Steps/index.ts
  src/views/studio/SelectMembershipView/StudioCard/StudioCard.style.ts
  src/views/studio/SelectMembershipView/StudioCard/StudioCard.tsx
  src/views/studio/SelectMembershipView/StudioCard/index.ts
  src/views/studio/SelectMembershipView/index.ts
  src/views/studio/SignInView/SignInView.style.ts
  src/views/studio/SignInView/SignInView.tsx
  src/views/studio/SignInView/fakeUtils.tsx
  src/views/studio/SignInView/index.ts
  src/views/studio/StudioLayout.tsx
Labels: review-approved
