Repository Joystream/atlas, pull requests merged in 2022-04, with the labels that each got.

#2359 Withdraw a bid
  packages/atlas/src/api/hooks/nfts.ts
  packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
  packages/atlas/src/hooks/useBlockTimeEstimation.ts
  packages/atlas/src/hooks/useNftState.ts
  packages/atlas/src/hooks/useNftTransactions.ts
  packages/atlas/src/views/global/NftPurchaseBottomDrawer/NftPurchaseBottomDrawer.tsx
  packages/atlas/src/views/playground/Playgrounds/PlaygroundEstimatingBlockTime.tsx
  packages/atlas/src/views/viewer/VideoView/VideoView.tsx
Labels: status:approved

#2413 Drawers should not cover the entire screen
  packages/atlas/src/components/_overlays/BottomDrawer/BottomDrawer.stories.tsx
  packages/atlas/src/components/_overlays/BottomDrawer/BottomDrawer.styles.ts
  packages/atlas/src/components/_overlays/BottomDrawer/BottomDrawer.tsx
  packages/atlas/src/views/global/NftPurchaseBottomDrawer/NftPurchaseBottomDrawer.tsx
  packages/atlas/src/views/global/NftSettlementBottomDrawer/NftSettlementBottomDrawer.tsx
Labels: status:approved

#2344 accept bid integration
  packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
  packages/atlas/src/components/_overlays/AcceptBidDialog/AcceptBidDialog.tsx
  packages/atlas/src/components/_overlays/AcceptBidDialog/AcceptBidDialog.types.ts
  packages/atlas/src/components/_overlays/AcceptBidDialog/AcceptBidList.tsx
  packages/atlas/src/hooks/useNftTransactions.ts
  packages/atlas/src/joystream-lib/extrinsics.ts
  packages/atlas/src/providers/nftActions/provider.tsx
Labels: status:approved

#2433 fix reviews bids button when no bids made
  packages/atlas/src/api/hooks/nfts.ts
  packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
Labels: status:approved

#2456 update sign in dialog
  packages/atlas/src/components/_illustrations/SignUpDialogIllustration.tsx
  packages/atlas/src/components/_illustrations/SignUpDialogPattern.tsx
  packages/atlas/src/components/_illustrations/index.tsx
  packages/atlas/src/components/_illustrations/svgs/sign-up-dialog-illustration.svg
  packages/atlas/src/components/_illustrations/svgs/sign-up-dialog-pattern.svg
  packages/atlas/src/hooks/useDisplaySignInDialog.tsx
Labels: status:approved

#2461 Fix `canBuyNow`
  packages/atlas/src/hooks/useNftState.ts
Labels: status:approved

#2435 cookies banner 🍪
  packages/atlas/src/AnalyticsManager.tsx
  packages/atlas/src/MainLayout.tsx
  packages/atlas/src/components/_navigation/BottomNav/BottomNav.tsx
  packages/atlas/src/components/_overlays/CookiePopover/CookiePopover.styles.ts
  packages/atlas/src/components/_overlays/CookiePopover/CookiePopover.tsx
  packages/atlas/src/components/_overlays/CookiePopover/index.ts
  packages/atlas/src/components/_overlays/Dialog/Dialog.tsx
  packages/atlas/src/providers/bottomNav.ts
  packages/atlas/src/providers/personalData/store.ts
  packages/atlas/src/providers/snackbars/snackbar.tsx
Labels: status:approved

#2484 Empty state for notification widget and view
  packages/atlas/src/components/_notifications/NotificationsWidget/NotificationsWidget.styles.ts
  packages/atlas/src/components/_notifications/NotificationsWidget/NotificationsWidget.tsx
  packages/atlas/src/views/notifications/Notifications.styles.ts
  packages/atlas/src/views/notifications/Notifications.tsx
Labels: status:approved

#2455 Async failed outcomes
  packages/atlas/src/components/_overlays/TransactionModal/TransactionModal.constants.ts
  packages/atlas/src/components/_overlays/TransactionModal/TransactionModal.tsx
  packages/atlas/src/joystream-lib/errors.ts
  packages/atlas/src/joystream-lib/helpers.ts
  packages/atlas/src/joystream-lib/types.ts
  packages/atlas/src/providers/transactionManager/store.ts
  packages/atlas/src/providers/transactionManager/transactionManager.tsx
  packages/atlas/src/providers/transactionManager/useTransaction.ts
  packages/atlas/src/views/global/NftPurchaseBottomDrawer/NftPurchaseBottomDrawer.tsx
  packages/atlas/src/views/global/NftSettlementBottomDrawer/NftSettlementBottomDrawer.tsx
  packages/atlas/src/views/playground/Playgrounds/PlaygroundNftExtrinsics.tsx
Labels: rhodes

#2417 Update royalties input in VideoForm
  packages/atlas/src/joystream-lib/helpers.ts
  packages/atlas/src/joystream-lib/lib.ts
  packages/atlas/src/providers/joystream/provider.tsx
  packages/atlas/src/providers/videoWorkspace/hooks.ts
  packages/atlas/src/views/global/NftPurchaseBottomDrawer/NftPurchaseBottomDrawer.tsx
  packages/atlas/src/views/studio/VideoWorkspace/VideoForm/VideoForm.tsx
Labels: rhodes

#2494 bid lock duration when changing bid
  packages/atlas/src/views/global/NftPurchaseBottomDrawer/NftPurchaseBottomDrawer.tsx
Labels: rhodes

#2430 Notif panel
  packages/atlas/src/components/_inputs/Checkbox/Checkbox.tsx
  packages/atlas/src/components/_notifications/NotificationTile/NotificationTile.tsx
  packages/atlas/src/components/_notifications/NotificationsWidget/NotificationsWidget.tsx
  packages/atlas/src/providers/notifications/notifications.hooks.ts
  packages/atlas/src/providers/notifications/notifications.store.ts
  packages/atlas/src/views/notifications/Notifications.hooks.ts
  packages/atlas/src/views/notifications/Notifications.tsx
  packages/atlas/src/views/notifications/NotificationsView.styles.ts
  packages/atlas/src/views/notifications/NotificationsView.tsx
  packages/atlas/src/views/notifications/index.ts
  packages/atlas/src/views/studio/StudioLayout.tsx
  packages/atlas/src/views/viewer/ViewerLayout.tsx
Labels: rhodes

#2466 Correct buttons on expired auction - Nft widget
  packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
  packages/atlas/src/hooks/useNftState.ts
Labels: rhodes

#2505 improve notifications fetching
  packages/atlas/src/api/hooks/notifications.ts
  packages/atlas/src/api/queries/__generated__/notifications.generated.tsx
  packages/atlas/src/api/queries/notifications.graphql
  packages/atlas/src/components/_navigation/NotificationsButton/NotificationsButton.tsx
  packages/atlas/src/components/_notifications/NotificationTile/NotificationTile.stories.tsx
  packages/atlas/src/components/_notifications/NotificationTile/NotificationTile.tsx
  packages/atlas/src/components/_notifications/NotificationsWidget/NotificationsWidget.tsx
  packages/atlas/src/components/_overlays/Popover/Popover.tsx
  packages/atlas/src/providers/notifications/notifications.hooks.ts
  packages/atlas/src/providers/notifications/notifications.manager.tsx
  packages/atlas/src/providers/notifications/notifications.store.ts
  packages/atlas/src/providers/notifications/notifications.types.ts
  packages/atlas/src/utils/number.ts
  packages/atlas/src/views/notifications/NotificationsView.tsx
Labels: rhodes

#2483 Update show more functionality on video page
  packages/atlas/src/views/viewer/VideoView/VideoView.styles.ts
  packages/atlas/src/views/viewer/VideoView/VideoView.tsx
Labels: status:approved

#2507 Remove temporary NFT data fetching
  packages/atlas/src/api/hooks/nfts.ts
  packages/atlas/src/api/queries/__generated__/nfts.generated.tsx
  packages/atlas/src/api/queries/nfts.graphql
  packages/atlas/src/components/FiltersBar/FiltersBar.tsx
  packages/atlas/src/components/FiltersBar/useFiltersBar.ts
  packages/atlas/src/components/_nft/NftTileViewer/NftTileViewer.tsx
  packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
  packages/atlas/src/components/_video/VideoTilePublisher/VideoTilePublisher.tsx
  packages/atlas/src/views/viewer/ChannelView/ChannelView.tsx
  packages/atlas/src/views/viewer/ChannelView/ChannelViewTabs/ChannelNfts.tsx
  packages/atlas/src/views/viewer/MemberView/MemberNFTs.tsx
  packages/atlas/src/views/viewer/MemberView/MemberView.tsx
  packages/atlas/src/views/viewer/VideoView/VideoView.tsx
Labels: rhodes

#2500 channel view NFT collectors
  packages/atlas/src/api/hooks/channel.ts
  packages/atlas/src/api/queries/__generated__/channels.generated.tsx
  packages/atlas/src/api/queries/channels.graphql
  packages/atlas/src/components/_channel/CollectorsBox/CollectorsBox.styles.ts
  packages/atlas/src/components/_channel/CollectorsBox/CollectorsBox.tsx
  packages/atlas/src/components/_nft/NftTile/NftTileDetails.tsx
  packages/atlas/src/views/viewer/ChannelView/ChannelView.tsx
Labels: status:approved, rhodes

#2508 Withdraw a bid from a past auction
  packages/atlas/src/api/hooks/bids.ts
  packages/atlas/src/api/hooks/nfts.ts
  packages/atlas/src/api/queries/__generated__/bids.generated.tsx
  packages/atlas/src/api/queries/__generated__/featured.generated.tsx
  packages/atlas/src/api/queries/__generated__/fragments.generated.tsx
  packages/atlas/src/api/queries/__generated__/nfts.generated.tsx
  packages/atlas/src/api/queries/__generated__/search.generated.tsx
  packages/atlas/src/api/queries/__generated__/videos.generated.tsx
  packages/atlas/src/api/queries/bids.graphql
  packages/atlas/src/api/queries/fragments.graphql
  packages/atlas/src/components/_nft/NftWidget/NftInfoItem.styles.ts
  packages/atlas/src/components/_nft/NftWidget/NftInfoItem.tsx
  packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
  packages/atlas/src/hooks/useNftState.ts
  packages/atlas/src/hooks/useNftTransactions.ts
  packages/atlas/src/views/viewer/VideoView/MoreVideos.tsx
Labels: rhodes

#2474 Comment component
  packages/atlas/src/components/Avatar/Avatar.tsx
  packages/atlas/src/components/Tooltip/Tooltip.tsx
  packages/atlas/src/components/_comments/Comment/Comment.stories.tsx
  packages/atlas/src/components/_comments/Comment/Comment.styles.ts
  packages/atlas/src/components/_comments/Comment/Comment.tsx
  packages/atlas/src/components/_comments/Comment/index.ts
Labels: status:approved

#2521 add NFT history integration
  packages/atlas/src/api/client/cache.ts
  packages/atlas/src/api/hooks/nfts.ts
  packages/atlas/src/api/queries/__generated__/notifications.generated.tsx
  packages/atlas/src/api/queries/notifications.graphql
  packages/atlas/src/components/_nft/NftWidget/NftHistory.styles.ts
  packages/atlas/src/components/_nft/NftWidget/NftHistory.tsx
  packages/atlas/src/components/_nft/NftWidget/NftWidget.hooks.ts
  packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
  packages/atlas/src/components/_nft/NftWidget/index.ts
  packages/atlas/src/views/viewer/VideoView/VideoView.tsx
Labels: status:approved

#2539 stop video autoplay when user is busy
  packages/atlas/src/components/_navigation/SidenavBase/SidenavBase.tsx
  packages/atlas/src/components/_video/VideoPlayer/VideoOverlay.tsx
  packages/atlas/src/components/_video/VideoPlayer/VideoOverlays/EndingOverlay.tsx
  packages/atlas/src/components/_video/VideoPlayer/VideoPlayer.tsx
  packages/atlas/src/providers/overlayManager.tsx
  packages/atlas/src/views/viewer/VideoView/VideoView.tsx
Labels: status:approved

#2550 Scroll to the top when changing steps in nft sale bottom drawer
  packages/atlas/src/components/ActionBar/ActionBar.styles.ts
  packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/NftForm.tsx
Labels: status:approved

#2562 upgrade types to 0.19.3
  .yarn/patches/@joystream-types-npm-0.19.2-3d8744373b
  .yarn/patches/@joystream-types-npm-0.19.3-e4e33d4bf2
  package.json
  packages/atlas/package.json
  yarn.lock
Labels: status:approved

#2567 Fix last item in CollectorBox
  packages/atlas/src/components/Avatar/AvatarGroup.tsx
Labels: status:approved

#2475 update tooltip component
  packages/atlas/src/components/ActionBar/ActionBar.tsx
  packages/atlas/src/components/Avatar/AvatarGroup.tsx
  packages/atlas/src/components/Information/Information.tsx
  packages/atlas/src/components/MembershipInfo/MembershipInfo.tsx
  packages/atlas/src/components/Tooltip/Tooltip.stories.tsx
  packages/atlas/src/components/Tooltip/Tooltip.styles.ts
  packages/atlas/src/components/Tooltip/Tooltip.tsx
  packages/atlas/src/components/_comments/Comment/Comment.tsx
  packages/atlas/src/views/global/NftPurchaseBottomDrawer/NftPurchaseBottomDrawer.tsx
  packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/AcceptTerms/AcceptTerms.tsx
  packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/SetUp/SetUp.tsx
  packages/atlas/src/views/studio/VideoWorkspace/VideoForm/VideoForm.tsx
Labels: status:approved

#2526 Comments section
  packages/atlas/src/api/hooks/comments.ts
  packages/atlas/src/api/hooks/index.ts
  packages/atlas/src/api/queries/__generated__/comments.generated.tsx
  packages/atlas/src/api/queries/__generated__/fragments.generated.tsx
  packages/atlas/src/api/queries/comments.graphql
  packages/atlas/src/api/queries/fragments.graphql
  packages/atlas/src/api/queries/index.ts
  packages/atlas/src/components/_comments/CommentRow/CommentRow.styles.ts
  packages/atlas/src/components/_comments/CommentRow/CommentRow.tsx
  packages/atlas/src/config/sorting.ts
  packages/atlas/src/views/viewer/VideoView/CommentsSection.tsx
  packages/atlas/src/views/viewer/VideoView/VideoView.styles.ts
  packages/atlas/src/views/viewer/VideoView/VideoView.tsx
Labels: status:approved
